### ISSUE TITLE
Rethink the issue templates

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/.github#14]
**Is your feature request related to a problem? Please describe.**

Users don't delete the template text of issues, which results in very long issues with a lot of noise.
One problem is that users don't have an "issue" that is outside of a predefined standard, except this small button that noone notices:

<img width="425" alt="Screen Shot 2020-08-27 at 10 19 14" src="https://user-images.githubusercontent.com/914122/91372522-cd703f00-e84e-11ea-939b-3559645b415b.png">

**Describe the solution you'd like**

I think we need another issue template for "other" that is light and helps in case the regular templates fail.

also I think it would be good if the issue templates would be structured in a way that suggests to delete the instructions, maybe like:

```
[Describe the solution you'd like: a clear and consise description of what you want to happen]
````

**Describe alternatives you've considered**

It might be possible to delete all issue templates, but that doesn't help too much either 😛 

**Additional context**

**Comment by chmac** [comment]
@martinheidegger You can wrap your suggestions in `<!-- ... -->` comment tags, then they won't be visible when you're browsing the issues, but will be seen by the user as they report an issue.

> One funny thing, I didn't want to submit a PR to fix #13 because then I'd have cloned this repo as `@chmac/.github` which is not something I wanted to do.

In terms of feedback, no harm in having an "Other" or "General" issue template. One thing that I personally assume when there are issue templates, is that other types of messages not welcome on the repo. We use this as a strategy in repos where we don't provide support for example.
